### ISSUE TITLE
Detached Networkinterfaces can not be reused

### ISSUE THREAD

**Issue by jerbel** [kortef/MoDMaCAO#7]
When posting a Networkinterface element which tries to use an already existing network port, it is not checked whether it is detached and may be reused.

Reproducing steps:
- Create Compute1
- Create Network1
- Create Networkinterface(Compute1->Network1)
- Delete Compute1 //Also deletes the Networkinterface in the model resulting in the detached network port
- Create Compute1
- Create Networkinterface(Compute1->Network1)

**Comment by kortef** [comment]
NetworkInterfaces (OpenStack Ports) can now created independently from Compute Resources in the model with a given runtime id. Such it becomes possible to reuse disconnected ports.
